/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-06-29 07:02:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MoneyDiary.material_005fable_002dmain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class auth_002dnormal_002dsign_002din_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title>맘대로!</title>\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 10]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("      <![endif]-->\n");
      out.write("      <!-- Meta -->\n");
      out.write("      <meta charset=\"utf-8\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("\n");
      out.write("      <meta name=\"keywords\" content=\"bootstrap, bootstrap admin template, admin theme, admin dashboard, dashboard template, admin template, responsive\" />\n");
      out.write("      <meta name=\"author\" content=\"Codedthemes\" />\n");
      out.write("      <!-- Favicon icon -->\n");
      out.write("\n");
      out.write("      <link rel=\"icon\" href=\"assets/images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("      <!-- Google font-->\n");
      out.write("      <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\n");
      out.write("      <!-- Required Fremwork -->\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/bootstrap/css/bootstrap.min.css\">\n");
      out.write("      <!-- waves.css -->\n");
      out.write("      <link rel=\"stylesheet\" href=\"assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\n");
      out.write("      <!-- themify-icons line icon -->\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/icon/themify-icons/themify-icons.css\">\n");
      out.write("      <!-- ico font -->\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/icon/icofont/css/icofont.css\">\n");
      out.write("      <!-- Font Awesome -->\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/icon/font-awesome/css/font-awesome.min.css\">\n");
      out.write("      <!-- Style.css -->\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\n");
      out.write("      \n");
      out.write("      <script>\n");
      out.write("	   \n");
      out.write("	    function signIn(){\n");
      out.write("	    	\n");
      out.write("	    	document.getElementById(\"form\").submit();\n");
      out.write("	    }\n");
      out.write("      </script>\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body themebg-pattern=\"theme1\">\n");
      out.write("  \n");
      out.write("  <!-- Pre-loader start -->\n");
      out.write("  <div class=\"theme-loader\">\n");
      out.write("      <div class=\"loader-track\">\n");
      out.write("          <div class=\"preloader-wrapper\">\n");
      out.write("              <div class=\"spinner-layer spinner-blue\">\n");
      out.write("                  <div class=\"circle-clipper left\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"gap-patch\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"circle-clipper right\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"spinner-layer spinner-red\">\n");
      out.write("                  <div class=\"circle-clipper left\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"gap-patch\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"circle-clipper right\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"spinner-layer spinner-yellow\">\n");
      out.write("                  <div class=\"circle-clipper left\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"gap-patch\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"circle-clipper right\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <div class=\"spinner-layer spinner-green\">\n");
      out.write("                  <div class=\"circle-clipper left\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"gap-patch\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"circle-clipper right\">\n");
      out.write("                      <div class=\"circle\"></div>\n");
      out.write("                  </div>\n");
      out.write("              </div>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("  </div>\n");
      out.write("  <!-- Pre-loader end -->\n");
      out.write("\n");
      out.write("    <section class=\"login-block\">\n");
      out.write("        <!-- Container-fluid starts -->\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-sm-12\">\n");
      out.write("                    <!-- Authentication card start -->\n");
      out.write("\n");
      out.write("                        <form id=\"form\" class=\"md-float-material form-material\" action=\"./login_ok.jsp\" method=\"post\">\n");
      out.write("                            <div class=\"text-center\">\n");
      out.write("                                <!-- <img src=\"assets/images/logo.png\" alt=\"logo.png\"> -->\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"auth-box card\">\n");
      out.write("                                <div class=\"card-block\">\n");
      out.write("                                    <div class=\"row m-b-20\">\n");
      out.write("                                        <div class=\"col-md-12\">\n");
      out.write("                                            <h3 class=\"text-center\">Sign In</h3>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"form-group form-primary\">\n");
      out.write("                                        <input type=\"text\" name=\"email\" class=\"form-control\">\n");
      out.write("                                        <span class=\"form-bar\"></span>\n");
      out.write("                                        <label class=\"float-label\">Your Email Address</label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"form-group form-primary\">\n");
      out.write("                                        <input type=\"password\" name=\"password\" class=\"form-control\">\n");
      out.write("                                        <span class=\"form-bar\"></span>\n");
      out.write("                                        <label class=\"float-label\">Password</label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"row m-t-25 text-left\">\n");
      out.write("                                        <div class=\"col-12\">\n");
      out.write("                                            <div class=\"checkbox-fade fade-in-primary d-\">\n");
      out.write("                                                <label>\n");
      out.write("                                                    <input type=\"checkbox\" value=\"\">\n");
      out.write("                                                    <span class=\"cr\"><i class=\"cr-icon icofont icofont-ui-check txt-primary\"></i></span>\n");
      out.write("                                                    <span class=\"text-inverse\">Remember me</span>\n");
      out.write("                                                </label>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"forgot-phone text-right f-right\">\n");
      out.write("                                                <a href=\"auth-reset-password.html\" class=\"text-right f-w-600\"> Forgot Password?</a>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"row m-t-30\">\n");
      out.write("                                        <div class=\"col-md-12\">\n");
      out.write("                                            <button type=\"button\" class=\"btn btn-primary btn-md btn-block waves-effect waves-light text-center m-b-20\" onclick=\"signIn();\">\n");
      out.write("                                            	Sign in\n");
      out.write("                                            </button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <hr/>\n");
      out.write("                                    <!-- \n");
      out.write("                                    <div class=\"row\">\n");
      out.write("                                        <div class=\"col-md-10\">\n");
      out.write("                                            <p class=\"text-inverse text-left m-b-0\">Thank you.</p>\n");
      out.write("                                            <p class=\"text-inverse text-left\"><a href=\"index.jsp\"><b>Back to website</b></a></p>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-2\">\n");
      out.write("                                            <img src=\"assets/images/auth/Logo-small-bottom.png\" alt=\"small-logo.png\">\n");
      out.write("                                        </div>\n");
      out.write("                                    </div> -->\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                        <!-- end of form -->\n");
      out.write("                </div>\n");
      out.write("                <!-- end of col-sm-12 -->\n");
      out.write("            </div>\n");
      out.write("            <!-- end of row -->\n");
      out.write("        </div>\n");
      out.write("        <!-- end of container-fluid -->\n");
      out.write("    </section>\n");
      out.write("    <!-- Warning Section Starts -->\n");
      out.write("    <!-- Older IE warning message -->\n");
      out.write("    <!--[if lt IE 10]>\n");
      out.write("<div class=\"ie-warning\">\n");
      out.write("    <h1>Warning!!</h1>\n");
      out.write("    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>\n");
      out.write("    <div class=\"iew-container\">\n");
      out.write("        <ul class=\"iew-download\">\n");
      out.write("            <li>\n");
      out.write("                <a href=\"http://www.google.com/chrome/\">\n");
      out.write("                    <img src=\"assets/images/browser/chrome.png\" alt=\"Chrome\">\n");
      out.write("                    <div>Chrome</div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"https://www.mozilla.org/en-US/firefox/new/\">\n");
      out.write("                    <img src=\"assets/images/browser/firefox.png\" alt=\"Firefox\">\n");
      out.write("                    <div>Firefox</div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"http://www.opera.com\">\n");
      out.write("                    <img src=\"assets/images/browser/opera.png\" alt=\"Opera\">\n");
      out.write("                    <div>Opera</div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"https://www.apple.com/safari/\">\n");
      out.write("                    <img src=\"assets/images/browser/safari.png\" alt=\"Safari\">\n");
      out.write("                    <div>Safari</div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("                <a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">\n");
      out.write("                    <img src=\"assets/images/browser/ie.png\" alt=\"\">\n");
      out.write("                    <div>IE (9 & above)</div>\n");
      out.write("                </a>\n");
      out.write("            </li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("    <p>Sorry for the inconvenience!</p>\n");
      out.write("</div>\n");
      out.write("<![endif]-->\n");
      out.write("<!-- Warning Section Ends -->\n");
      out.write("<!-- Required Jquery -->\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/jquery/jquery.min.js \"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/jquery-ui/jquery-ui.min.js \"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/popper.js/popper.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/bootstrap/js/bootstrap.min.js \"></script>\n");
      out.write("<!-- waves js -->\n");
      out.write("<script src=\"assets/pages/waves/js/waves.min.js\"></script>\n");
      out.write("<!-- jquery slimscroll js -->\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/jquery-slimscroll/jquery.slimscroll.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"assets/js/common-pages.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
