/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-06-29 01:21:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MoneyDiary.material_005fable_002dmain;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.text.DecimalFormat;

public final class bs_002dbasic_002dtable2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      Pkg_DB.DBHandle DBConn = null;
      DBConn = (Pkg_DB.DBHandle) _jspx_page_context.getAttribute("DBConn", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (DBConn == null){
        DBConn = new Pkg_DB.DBHandle();
        _jspx_page_context.setAttribute("DBConn", DBConn, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title>맘대로 !</title>\n");
      out.write("    ");

    	request.setCharacterEncoding("UTF-8");
		DecimalFormat price = new DecimalFormat("###,###,###");
		
		String strUserId = (String)session.getAttribute("userId");

		if(strUserId == null){
    		response.sendRedirect("./auth-normal-sign-in.jsp");
    	}
    	
    	String strDate = "21-04-10";
    	//System.out.println(strUserId);

		String[] dbInfos = new String[3];
		dbInfos[0] = "jdbc:oracle:thin:@localhost:1521:xe";
		dbInfos[1] = "money_diary";
		dbInfos[2] = "1";
	
		DBConn.setDBInfo(dbInfos);
		
		//해당 월 일별 상세 내역
		String strProcName = "{call PKG_SEL_DIARY.PROC_SEL_DETAIL(?,?,?)}";
		
		String[] strParams = new String[2];
		strParams[0] = strUserId;
		strParams[1] = strDate;
		
		ResultSet rs = DBConn.getResultSet(strProcName, strParams);
		
		// 해당 월 총계
		String strProcName2 = "{call PKG_SEL_DIARY.PROC_SEL_MONTH(?,?,?)}";
		
		String[] strParams2 = new String[2];
		strParams2[0] = strUserId;
		strParams2[1] = strDate;
		
		ResultSet rs2 = DBConn.getResultSet(strProcName2, strParams2);
		rs2.next();
		// 해당 월 일별 내역
		String strProcName3 = "{call PKG_SEL_DIARY.PROC_DAY_MONTH(?,?,?)}";
		
		String[] strParams3 = new String[2];
		strParams3[0] = strUserId;
		strParams3[1] = strDate;
		
		ResultSet rs3 = DBConn.getResultSet(strProcName3, strParams3);

    
      out.write("\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE10 support of HTML5 elements and media queries -->\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\n");
      out.write("    <!--[if lt IE 10]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\n");
      out.write("      <![endif]-->\n");
      out.write("    <!-- Meta -->\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("\n");
      out.write("    <meta name=\"keywords\" content=\"bootstrap, bootstrap admin template, admin theme, admin dashboard, dashboard template, admin template, responsive\" />\n");
      out.write("    <meta name=\"author\" content=\"Codedthemes\" />\n");
      out.write("    <!-- Favicon icon -->\n");
      out.write("    <link rel=\"icon\" href=\"assets/images/favicon.ico\" type=\"image/x-icon\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:400,600,700\" rel=\"stylesheet\">\n");
      out.write("    <!-- waves.css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\n");
      out.write("    <!-- Required Fremwork -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/bootstrap/css/bootstrap.min.css\">\n");
      out.write("    <!-- waves.css -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/pages/waves/css/waves.min.css\" type=\"text/css\" media=\"all\">\n");
      out.write("    <!-- themify-icons line icon -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/icon/themify-icons/themify-icons.css\">\n");
      out.write("    <!-- Font Awesome -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/icon/font-awesome/css/font-awesome.min.css\">\n");
      out.write("    <!-- ico font -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/icon/icofont/css/icofont.css\">\n");
      out.write("    <!-- Style.css -->\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.css\">\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/jquery.mCustomScrollbar.css\">\n");
      out.write("    <style>\n");
      out.write("        @font-face {font-family: \"BMHANNA\"; src: url (\"../font/BMHANNAAir_ttf.ttf\")}\n");
      out.write("        body {\n");
      out.write("            font-family: \"BMHANNA\";\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        window.onload = function(){\n");
      out.write("            $(\"body\").append('<div class=\"fixed-button active\"><a href=\"./index.jsp\" target=\"_blank\" class=\"btn btn-md btn-primary\">ìë£</a> </div>');\n");
      out.write("            var $window=$(window),nav=$(\".fixed-button\");\n");
      out.write("        };\n");
      out.write("        \n");
      out.write("        /* import html with ajax */\n");
      out.write("	    function includeHTML() {\n");
      out.write("	    	  var z, i, elmnt, file, xhttp;\n");
      out.write("	    	  /*loop through a collection of all HTML elements:*/\n");
      out.write("	    	  z = document.getElementsByTagName(\"*\");\n");
      out.write("	    	  for (i = 0; i < z.length; i++) {\n");
      out.write("	    	    elmnt = z[i];\n");
      out.write("	    	    /*search for elements with a certain atrribute:*/\n");
      out.write("	    	    file = elmnt.getAttribute(\"include-html\");\n");
      out.write("	    	    if (file) {\n");
      out.write("	    	      /*make an HTTP request using the attribute value as the file name:*/\n");
      out.write("	    	      xhttp = new XMLHttpRequest();\n");
      out.write("	    	      xhttp.onreadystatechange = function() {\n");
      out.write("	    	        if (this.readyState == 4) {\n");
      out.write("	    	          if (this.status == 200) {elmnt.innerHTML = this.responseText;}\n");
      out.write("	    	          if (this.status == 404) {elmnt.innerHTML = \"Page not found.\";}\n");
      out.write("	    	          /*remove the attribute, and call this function once more:*/\n");
      out.write("	    	          elmnt.removeAttribute(\"include-html\");\n");
      out.write("	    	          includeHTML();\n");
      out.write("	    	        }\n");
      out.write("	    	      }      \n");
      out.write("	    	      xhttp.open(\"GET\", file, true);\n");
      out.write("	    	      xhttp.send();\n");
      out.write("	    	      /*exit the function:*/\n");
      out.write("	    	      return;\n");
      out.write("	    	    }\n");
      out.write("	    	  }\n");
      out.write("	    	};\n");
      out.write("	    /* import html with ajax */\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("    <!-- Pre-loader start -->\n");
      out.write("    <div class=\"theme-loader\">\n");
      out.write("        <div class=\"loader-track\">\n");
      out.write("            <div class=\"preloader-wrapper\">\n");
      out.write("                <div class=\"spinner-layer spinner-blue\">\n");
      out.write("                    <div class=\"circle-clipper left\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"gap-patch\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"circle-clipper right\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"spinner-layer spinner-red\">\n");
      out.write("                    <div class=\"circle-clipper left\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"gap-patch\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"circle-clipper right\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"spinner-layer spinner-yellow\">\n");
      out.write("                    <div class=\"circle-clipper left\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"gap-patch\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"circle-clipper right\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"spinner-layer spinner-green\">\n");
      out.write("                    <div class=\"circle-clipper left\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"gap-patch\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"circle-clipper right\">\n");
      out.write("                        <div class=\"circle\"></div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Pre-loader end -->\n");
      out.write("    <div id=\"pcoded\" class=\"pcoded\">\n");
      out.write("        <div class=\"pcoded-overlay-box\"></div>\n");
      out.write("        <div class=\"pcoded-container navbar-wrapper\">\n");
      out.write("            <nav class=\"navbar header-navbar pcoded-header\">\n");
      out.write("                <div class=\"navbar-wrapper\">\n");
      out.write("                    <div class=\"navbar-logo\">\n");
      out.write("                        <a class=\"mobile-menu waves-effect waves-light\" id=\"mobile-collapse\" href=\"#!\">\n");
      out.write("                            <i class=\"ti-menu\"></i>\n");
      out.write("                        </a>\n");
      out.write("                        <div class=\"mobile-search waves-effect waves-light\">\n");
      out.write("                            <div class=\"header-search\">\n");
      out.write("                                <div class=\"main-search morphsearch-search\">\n");
      out.write("                                    <div class=\"input-group\">\n");
      out.write("                                        <span class=\"input-group-prepend search-close\"><i class=\"ti-close input-group-text\"></i></span>\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Enter Keyword\">\n");
      out.write("                                        <span class=\"input-group-append search-btn\"><i class=\"ti-search input-group-text\"></i></span>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <!--<a href=\"index.jsp\">\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/images/logo.png\" alt=\"Theme-Logo\" />\n");
      out.write("                        </a>-->\n");
      out.write("                        <a class=\"mobile-options waves-effect waves-light\">\n");
      out.write("                            <i class=\"ti-more\"></i>\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"navbar-container container-fluid\">\n");
      out.write("                        <ul class=\"nav-left\">\n");
      out.write("                            <li>\n");
      out.write("                                <div class=\"sidebar_toggle\"><a href=\"javascript:void(0)\"><i class=\"ti-menu\"></i></a></div>\n");
      out.write("                            </li>\n");
      out.write("                            <!--<li>\n");
      out.write("                                <a href=\"#!\" onclick=\"javascript:toggleFullScreen()\" class=\"waves-effect waves-light\">\n");
      out.write("                                    <i class=\"ti-fullscreen\"></i>\n");
      out.write("                                </a>\n");
      out.write("                            </li>-->\n");
      out.write("                        </ul>\n");
      out.write("                        <ul>\n");
      out.write("                            <!-- Page-header start --><!-- ëª¨ë°ì¼ìì ê¹¨ì ¸ì -->\n");
      out.write("                            <li>\n");
      out.write("                                <span style=\"width:25%;display:block;float:left;padding-top:0.8%;\">\n");
      out.write("                                    <h4 style=\"text-align:center;color:rgb(255,252,244);\">&#60;</h4>\n");
      out.write("                                </span>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                    <span style=\"width:30%;display:block;float:left;padding-top:0.7%;\">\n");
      out.write("                                    <h4 style=\"text-align:center;padding-top:5px;color:rgb(255,252,244);\">2021.04.01 ~ 4.30</h4>\n");
      out.write("                                </span>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <span style=\"width:12%;display:block;float:left;padding-top:0.8%;\">\n");
      out.write("                                    <h4 style=\"text-align:right;color:rgb(255,252,244);\">&#62;</h4>\n");
      out.write("                                </span>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                        <ul class=\"nav-right\">\n");
      out.write("                            <!--\n");
      out.write("                            <li class=\"header-notification\">\n");
      out.write("                                <a href=\"#!\" class=\"waves-effect waves-light\">\n");
      out.write("                                    <i class=\"ti-bell\"></i>\n");
      out.write("                                    <span class=\"badge bg-c-red\"></span>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"show-notification\">\n");
      out.write("                                    <li>\n");
      out.write("                                        <h6>Notifications</h6>\n");
      out.write("                                        <label class=\"label label-danger\">New</label>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <div class=\"media\">\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"assets/images/avatar-2.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                                            <div class=\"media-body\">\n");
      out.write("                                                <h5 class=\"notification-user\">John Doe</h5>\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <div class=\"media\">\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"assets/images/avatar-4.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                                            <div class=\"media-body\">\n");
      out.write("                                                <h5 class=\"notification-user\">Joseph William</h5>\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <div class=\"media\">\n");
      out.write("                                            <img class=\"d-flex align-self-center img-radius\" src=\"assets/images/avatar-3.jpg\" alt=\"Generic placeholder image\">\n");
      out.write("                                            <div class=\"media-body\">\n");
      out.write("                                                <h5 class=\"notification-user\">Sara Soudein</h5>\n");
      out.write("                                                <p class=\"notification-msg\">Lorem ipsum dolor sit amet, consectetuer elit.</p>\n");
      out.write("                                                <span class=\"notification-time\">30 minutes ago</span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>-->\n");
      out.write("                            <li class=\"user-profile header-notification\">\n");
      out.write("                                <a href=\"#!\" class=\"waves-effect waves-light\">\n");
      out.write("                                    <img src=\"assets/images/profile.jpg\" class=\"img-radius\" alt=\"User-Profile-Image\">\n");
      out.write("                                    <span>");
      out.print(strUserId );
      out.write("</span>\n");
      out.write("                                    <i class=\"ti-angle-down\"></i>\n");
      out.write("                                </a>\n");
      out.write("                                <ul class=\"show-notification profile-notification\">\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <a href=\"#!\">\n");
      out.write("                                            <i class=\"ti-settings\"></i> Settings\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <a href=\"user-profile.html\">\n");
      out.write("                                            <i class=\"ti-user\"></i> Profile\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <a href=\"email-inbox.html\">\n");
      out.write("                                            <i class=\"ti-email\"></i> My Messages\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <a href=\"auth-lock-screen.html\">\n");
      out.write("                                            <i class=\"ti-lock\"></i> Lock Screen\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                    <li class=\"waves-effect waves-light\">\n");
      out.write("                                        <a href=\"auth-normal-sign-in.jsp\">\n");
      out.write("                                            <i class=\"ti-layout-sidebar-left\"></i> Logout\n");
      out.write("                                        </a>\n");
      out.write("                                    </li>\n");
      out.write("                                </ul>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </nav>\n");
      out.write("            <div class=\"pcoded-main-container\">\n");
      out.write("                <div class=\"pcoded-wrapper\">\n");
      out.write("                    <nav class=\"pcoded-navbar\">\n");
      out.write("                        <div class=\"sidebar_toggle\"><a href=\"#\"><i class=\"icon-close icons\"></i></a></div>\n");
      out.write("                        <div class=\"pcoded-inner-navbar main-menu\">\n");
      out.write("                            <div class=\"\">\n");
      out.write("                                <div class=\"main-menu-header\">\n");
      out.write("                                    <img class=\"img-80 img-radius\" src=\"assets/images/profile.jpg\" alt=\"User-Profile-Image\">\n");
      out.write("                                    <div class=\"user-details\">\n");
      out.write("                                        <span id=\"more-details\" style=\"color:#666;\">");
      out.print(strUserId );
      out.write("<i class=\"fa fa-caret-down\"></i></span>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"main-menu-content\">\n");
      out.write("                                    <ul>\n");
      out.write("                                        <li class=\"more-details\">\n");
      out.write("                                            <a href=\"user-profile.html\"><i class=\"ti-user\"></i>View Profile</a>\n");
      out.write("                                            <a href=\"#!\"><i class=\"ti-settings\"></i>Settings</a>\n");
      out.write("                                            <a href=\"auth-normal-sign-in.jsp\"><i class=\"ti-layout-sidebar-left\"></i>Logout</a>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"p-15 p-b-0\">\n");
      out.write("                                <form class=\"form-material\">\n");
      out.write("                                    <div class=\"form-group form-primary\">\n");
      out.write("                                        <input type=\"text\" name=\"footer-email\" class=\"form-control\">\n");
      out.write("                                        <span class=\"form-bar\"></span>\n");
      out.write("                                        <label class=\"float-label\"><i class=\"fa fa-search m-r-10\"></i>Search</label>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                            <!--<div class=\"pcoded-navigation-label\">Navigation</div>-->\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\n");
      out.write("                                <li class=\"\">\n");
      out.write("                                    <a href=\"index.jsp\" class=\"waves-effect waves-dark\">\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-home\"></i><b>D</b></span>\n");
      out.write("                                        <span class=\"pcoded-mtext\">Home</span>\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!--<div class=\"pcoded-navigation-label\">Tables</div>-->\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\n");
      out.write("                                <li class=\"active\">\n");
      out.write("                                    <a href=\"bs-basic-table2.jsp\" class=\"waves-effect waves-dark\">\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-receipt\"></i><b>B</b></span>\n");
      out.write("                                        <span class=\"pcoded-mtext\">Detail</span>\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\n");
      out.write("                                <li class=\"\">\n");
      out.write("                                    <a href=\"modify.jsp\" class=\"waves-effect waves-dark\">\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-receipt\"></i><b>B</b></span>\n");
      out.write("                                        <span class=\"pcoded-mtext\">modify</span>\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!--<div class=\"pcoded-navigation-label\">Chart And Maps</div>-->\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\n");
      out.write("                                <li class=\"\">\n");
      out.write("                                    <a href=\"chart-morris.html\" class=\"waves-effect waves-dark\">\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-bar-chart-alt\"></i><b>C</b></span>\n");
      out.write("                                        <span class=\"pcoded-mtext\">Charts</span>\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                            <!--<div class=\"pcoded-navigation-label\">Pages</div>-->\n");
      out.write("                            <ul class=\"pcoded-item pcoded-left-item\">\n");
      out.write("                                <li class=\"pcoded-hasmenu \">\n");
      out.write("                                    <a href=\"javascript:void(0)\" class=\"waves-effect waves-dark\">\n");
      out.write("                                        <span class=\"pcoded-micon\"><i class=\"ti-id-badge\"></i><b>A</b></span>\n");
      out.write("                                        <span class=\"pcoded-mtext\">Login</span>\n");
      out.write("                                        <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                    </a>\n");
      out.write("                                    <ul class=\"pcoded-submenu\">\n");
      out.write("                                        <li class=\"\">\n");
      out.write("                                            <a href=\"auth-normal-sign-in.jsp\" class=\"waves-effect waves-dark\">\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\n");
      out.write("                                                <span class=\"pcoded-mtext\">Login</span>\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li class=\"\">\n");
      out.write("                                            <a href=\"auth-sign-up.html\" class=\"waves-effect waves-dark\">\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-angle-right\"></i></span>\n");
      out.write("                                                <span class=\"pcoded-mtext\">Registration</span>\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                        <li class=\"\">\n");
      out.write("                                            <a href=\"sample-page.html\" class=\"waves-effect waves-dark\">\n");
      out.write("                                                <span class=\"pcoded-micon\"><i class=\"ti-layout-sidebar-left\"></i><b>S</b></span>\n");
      out.write("                                                <span class=\"pcoded-mtext\">Sample Page</span>\n");
      out.write("                                                <span class=\"pcoded-mcaret\"></span>\n");
      out.write("                                            </a>\n");
      out.write("                                        </li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </nav>\n");
      out.write("                    <div class=\"pcoded-content\">\n");
      out.write("                        <!-- Page-header end -->\n");
      out.write("                        <div class=\"pcoded-inner-content\">\n");
      out.write("                            <!-- Main-body start -->\n");
      out.write("                            <div class=\"main-body\">\n");
      out.write("                                <div class=\"page-wrapper\">\n");
      out.write("                                    <!-- Page-body start -->\n");
      out.write("                                    <div class=\"page-body\">\n");
      out.write("                                                <div class=\"card mat-stat-card\">\n");
      out.write("                                                    <div class=\"card-block\">\n");
      out.write("                                                        <div class=\"row align-items-center b-b-default\">\n");
      out.write("                                                            <!-- box 1 -->\n");
      out.write("                                                            <div class=\"col-sm-6 b-r-default p-b-20 p-t-20\" style=\"background-color:#67D5B5;\">\n");
      out.write("                                                                \n");
      out.write("                                                                    <div class=\"col-12 p-m-0\" style=\"color:rgb(255,252,244);text-align:center;padding-left:0px;padding-right:0px\">\n");
      out.write("                                                                        <h5>");
      out.print(price.format(Integer.parseInt(rs2.getString("INCOME"))) );
      out.write("</h5>\n");
      out.write("                                                                        <h7>");
      out.print(rs2.getString("ICNT") );
      out.write("건</h7>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                \n");
      out.write("                                                            </div>\n");
      out.write("                                                            <!-- box 2 -->\n");
      out.write("                                                            <div class=\"col-sm-6 p-b-20 p-t-20\" style=\"background-color:#EE7785;\">\n");
      out.write("                                                                <div class=\"row align-items-center text-center\">\n");
      out.write("                                                                    <div class=\"col-12 p-l-0\" style=\"color:rgb(255,252,244);text-align:center;padding-right:0px\">\n");
      out.write("                                                                        <h5>");
      out.print(price.format(Integer.parseInt(rs2.getString("OUTCOME"))) );
      out.write("</h5>\n");
      out.write("                                                                        <h7>");
      out.print(rs2.getString("OCNT") );
      out.write("건</h7>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                        <div class=\"row align-items-center\">\n");
      out.write("                                                            <!-- box 3 -->\n");
      out.write("                                                            <div class=\"col-sm-12 p-b-30 p-t-30 b-r-default\">\n");
      out.write("                                                                <div class=\"row align-items-center text-center\">\n");
      out.write("                                                                    <div class=\"col-12 p-l-20\" style=\"padding-right:0px\">\n");
      out.write("                                                                        <h5 style=\"margin-bottom:0px;\">");
      out.print(price.format(Integer.parseInt(rs2.getString("TLTPRICE"))) );
      out.write("</h5>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                </div>\n");
      out.write("                                                            </div>\n");
      out.write("                                                        </div>\n");
      out.write("                                                    </div>\n");
      out.write("                                                </div>\n");
      out.write("                                            \n");
      out.write("                                        <!-- Basic table card start -->\n");
      out.write("                                        <div class=\"card\">\n");
      out.write("                                            <div class=\"card-header\" style=\"background-color:#cff09e\">\n");
      out.write("                                                <h4 style=\"margin-top:5px\">가계부 자세히 보기</h4>\n");
      out.write("                                                <div class=\"card-header-right\">\n");
      out.write("                                                    <ul class=\"list-unstyled card-option\">\n");
      out.write("                                                        <li><i class=\"fa fa fa-wrench open-card-option\"></i></li>\n");
      out.write("                                                        <li><i class=\"fa fa-window-maximize full-card\"></i></li>\n");
      out.write("                                                        <li><i class=\"fa fa-minus minimize-card\"></i></li>\n");
      out.write("                                                        <li><i class=\"fa fa-refresh reload-card\"></i></li>\n");
      out.write("                                                        <li><i class=\"fa fa-trash close-card\"></i></li>\n");
      out.write("                                                    </ul>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"card-block table-border-style\">\n");
      out.write("                                                <div class=\"table-responsive\">\n");
      out.write("                                                	\n");
      out.write("                                                	");
  //th 생성기준
                                                		String tmpDate = "";
                                                		while(rs.next()){
                                                			String dd = rs.getString("MN_DATE");
                                                			String COME = "";
                                                			if(!tmpDate.equals(dd)){
                                                				if(!tmpDate.equals("")){
                                                	
      out.write("\n");
      out.write("                                                					</tbody>\n");
      out.write("                                                				</table>\n");
      out.write("                                                	");

                                                				}
                                                				tmpDate = dd;
                                                				rs3.next();
                                                	
      out.write("\n");
      out.write("                                                		<table class=\"table\">\n");
      out.write("                                                        <thead>\n");
      out.write("                                                            <tr>\n");
      out.write("                                                                <th style=\"width:25%;padding:2px2px2px2px;vertical-align:middle;\">\n");
      out.write("                                                                    <h5 class=\"f-w-700\" style=\"margin-bottom:0px;\">\n");
      out.write("                                                                        ");
      out.print(tmpDate );
      out.write("\n");
      out.write("                                                                    </h5>\n");
      out.write("                                                                </th>\n");
      out.write("                                                                <th style=\"width:25%\">\n");
      out.write("\n");
      out.write("                                                                </th>\n");
      out.write("                                                                <th style=\"width:25%;padding:2px 2px 5px 2px;\">\n");
      out.write("                                                                    <h5 class=\"f-w-700\" style=\"color:blue;text-align:center;padding-top:8px;\">\n");
      out.write("                                                                		");
      out.print(price.format(Integer.parseInt(rs3.getString("INCOME"))) );
      out.write("\n");
      out.write("                                                                    </h5>\n");
      out.write("                                                                </th>\n");
      out.write("                                                                <th style=\"width:25%;padding:2px 2px 5px 2px;\">\n");
      out.write("                                                                    <h5 class=\"f-w-700\" style=\"color:red;text-align:center;padding-top:8px;\">\n");
      out.write("                                                                        ");
      out.print(price.format(Integer.parseInt(rs3.getString("OUTCOME"))) );
      out.write("\n");
      out.write("                                                                    </h5>\n");
      out.write("                                                                </th>\n");
      out.write("                                                            </tr>\n");
      out.write("                                                        </thead>\n");
      out.write("                                                        <tbody>\n");
      out.write("                                                        ");

                                                			}
                                                        	if(rs.getString("INOUT").equals("O")){
                                                        
      out.write("\n");
      out.write("                                                        \n");
      out.write("                                                            <tr>\n");
      out.write("                                                                <th scope=\"row\" style=\"width:25%;vertical-align:middle;font-size:18px;\">\n");
      out.write("                                                                      ");
      out.print(rs.getString("C_NAME") );
      out.write("\n");
      out.write("                                                                </th>\n");
      out.write("                                                                <td style=\"width:25%;padding:0px0px0px0px;vertical-align:middle;\">\n");
      out.write("                                                                    <div>\n");
      out.write("                                                                        <span style=\"font-size:15px;font-weight:bold;\">\n");
      out.write("                                                                            ");
      out.print( rs.getString("M_CONTENT") );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                        &nbsp;&nbsp;&nbsp;\n");
      out.write("                                                                        <span class=\"text-muted m-b-0\" style=\"font-size:12px;\">\n");
      out.write("                                                                            ");

                                                                               String etc = "";
                                                                                            
                                                                               if(rs.getString("M_ETC") != null){
                                                                               		etc = rs.getString("M_ETC");
                                                                                	//System.out.println("null");
                                                                                } 
                                                                            
      out.write("\n");
      out.write("                                                                            ");
      out.print(etc );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                    <div>\n");
      out.write("                                                                        <span class=\"text-muted m-b-0\">\n");
      out.write("                                                                            ");
      out.print(rs.getString("MDATE") );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                        &nbsp;&nbsp;&nbsp;\n");
      out.write("                                                                        <span class=\"text-muted m-b-0\">\n");
      out.write("                                                                            ");
      out.print(rs.getString("P_NAME") );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                </td>\n");
      out.write("                                                                <td style=\"width:25%;color:blue;text-align:center;vertical-align:middle;\">\n");
      out.write("\n");
      out.write("                                                                </td>\n");
      out.write("                                                                <td style=\"width:25%;color:red;text-align:center;vertical-align:middle;\">\n");
      out.write("                                                                    ");
      out.print(price.format(Integer.parseInt(rs.getString("M_PRICE"))) );
      out.write("\n");
      out.write("                                                                </td>\n");
      out.write("                                                            </tr>\n");
      out.write("                                                            ");

                                                        		}else{
                                                            
      out.write("\n");
      out.write("                                                            <tr>\n");
      out.write("                                                                <th scope=\"row\" style=\"width:25%;vertical-align:middle;font-size:18px;\">\n");
      out.write("                                                                        ");
      out.print(rs.getString("C_NAME") );
      out.write("\n");
      out.write("                                                                </th>\n");
      out.write("                                                                <td style=\"width:25%;padding:0px0px0px0px;vertical-align:middle;\">\n");
      out.write("                                                                    <div>\n");
      out.write("                                                                        <span style=\"font-size:15px;font-weight:bold;\">\n");
      out.write("                                                                            ");
      out.print( rs.getString("M_CONTENT") );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                        &nbsp;&nbsp;&nbsp;\n");
      out.write("                                                                        <span class=\"text-muted m-b-0\" style=\"font-size:12px;\">\n");
      out.write("                                                                            ");

                                                                               String etc = "";
                                                                                            
                                                                               if(rs.getString("M_ETC") != null){
                                                                               		etc = rs.getString("M_ETC");
                                                                                	//System.out.println("null");
                                                                                } 
                                                                            
      out.write("\n");
      out.write("                                                                            ");
      out.print(etc );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                    <div>\n");
      out.write("                                                                        <span class=\"text-muted m-b-0\">\n");
      out.write("                                                                            ");
      out.print(rs.getString("MDATE") );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                        &nbsp;&nbsp;&nbsp;\n");
      out.write("                                                                        <span class=\"text-muted m-b-0\">\n");
      out.write("                                                                            ");
      out.print(rs.getString("P_NAME") );
      out.write("\n");
      out.write("                                                                        </span>\n");
      out.write("                                                                    </div>\n");
      out.write("                                                                </td>\n");
      out.write("                                                                <td style=\"width:25%;color:blue;text-align:center;vertical-align:middle;\">\n");
      out.write("                                                                    ");
      out.print(price.format(Integer.parseInt(rs.getString("M_PRICE"))) );
      out.write("\n");
      out.write("                                                                </td>\n");
      out.write("                                                                <td style=\"width:25%;color:red;text-align:center;vertical-align:middle;\">\n");
      out.write("                                                                   \n");
      out.write("                                                                </td>\n");
      out.write("                                                            </tr>\n");
      out.write("                                                            ");

                                                        		}
                                                			}
                                                        	
      out.write("\n");
      out.write("                                                        	\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <!-- Basic table card end -->\n");
      out.write("                                    </div>\n");
      out.write("                                    <!-- Page-body end -->\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Main-body end -->\n");
      out.write("\n");
      out.write("                            <div id=\"styleSelector\">\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Warning Section Starts -->\n");
      out.write("    <!-- Older IE warning message -->\n");
      out.write("    <!--[if lt IE 10]>\n");
      out.write("    <div class=\"ie-warning\">\n");
      out.write("        <h1>Warning!!</h1>\n");
      out.write("        <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>\n");
      out.write("        <div class=\"iew-container\">\n");
      out.write("            <ul class=\"iew-download\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"http://www.google.com/chrome/\">\n");
      out.write("                        <img src=\"assets/images/browser/chrome.png\" alt=\"Chrome\">\n");
      out.write("                        <div>Chrome</div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"https://www.mozilla.org/en-US/firefox/new/\">\n");
      out.write("                        <img src=\"assets/images/browser/firefox.png\" alt=\"Firefox\">\n");
      out.write("                        <div>Firefox</div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"http://www.opera.com\">\n");
      out.write("                        <img src=\"assets/images/browser/opera.png\" alt=\"Opera\">\n");
      out.write("                        <div>Opera</div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"https://www.apple.com/safari/\">\n");
      out.write("                        <img src=\"assets/images/browser/safari.png\" alt=\"Safari\">\n");
      out.write("                        <div>Safari</div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"http://windows.microsoft.com/en-us/internet-explorer/download-ie\">\n");
      out.write("                        <img src=\"assets/images/browser/ie.png\" alt=\"\">\n");
      out.write("                        <div>IE (9 & above)</div>\n");
      out.write("                    </a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("        <p>Sorry for the inconvenience!</p>\n");
      out.write("    </div>\n");
      out.write("    <![endif]-->\n");
      out.write("    <!-- Warning Section Ends -->\n");
      out.write("    <!-- Required Jquery -->\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/jquery/jquery.min.js \"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/jquery-ui/jquery-ui.min.js \"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/popper.js/popper.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/bootstrap/js/bootstrap.min.js \"></script>\n");
      out.write("    <!-- waves js -->\n");
      out.write("    <script src=\"assets/pages/waves/js/waves.min.js\"></script>\n");
      out.write("    <!-- jquery slimscroll js -->\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/jquery-slimscroll/jquery.slimscroll.js\"></script>\n");
      out.write("    <!-- Custom js -->\n");
      out.write("    <script src=\"assets/js/pcoded.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/vertical/vertical-layout.min.js\"></script>\n");
      out.write("    <script src=\"assets/js/jquery.mCustomScrollbar.concat.min.js\"></script>\n");
      out.write("    <script type=\"text/javascript\" src=\"assets/js/script.js\"></script>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
